[package]
name = "daw-engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.15.2"
itertools = "0.11.0"
midir = "0.9.1"
rand = "0.8.5"
